version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user
  # BeforeInstall은 제거하고 AfterInstall을 추가합니다.
  AfterInstall:
    - location: scripts/set_permissions.sh # 우리가 만든 권한 부여 스크립트
      timeout: 60
      runas: root # 파일 권한 변경은 root 권한으로 실행
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user