# \uBC30\uD3EC \uBE4C\uB4DC \uC124\uC815
spring.config.import=aws-secretsmanager:tio/db/credentials,aws-secretsmanager:tio/oauth/google,aws-secretsmanager:tio/jwt,aws-secretsmanager:tio/mail,aws-secretsmanager:tio/payments/toss,aws-secretsmanager:tio/secret
# AWS Secrets Manager \uBBFC\uAC10 \uC815\uBCF4 \uAC00\uC838\uC624\uAE30

# springboot devtools \uBE44\uD65C\uC131\uD654 (ec2 \uBC30\uD3EC \uD658\uACBD\uC5D0\uC11C\uB294 \uBD88\uD544\uC694)
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# JPA \uC124\uC815
# \uC808\uB300 \uBCC0\uACBD \uAE08\uC9C0
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# \uC2E4\uC81C \uBC30\uD3EC\uB41C FastAPI \uC11C\uBC84 \uC8FC\uC18C
FastApi.user-service.url=http://10.0.163.170:8000

# AWS Redis
spring.data.redis.host=${REDIS_URL}
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.ssl.enabled=true
spring.data.redis.ssl.protocols=TLSv1.2
spring.data.redis.ssl.verify-peer=false
spring.data.redis.ssl.endpoint-identification-enabled=false
spring.data.redis.timeout=60000
spring.data.redis.connect-timeout=60000
spring.data.redis.lettuce.shutdown-timeout=60000

# Lettuce
spring.data.redis.lettuce.cluster.verify-hostname=false

spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.max-wait=-1ms

# Cache Redis Configuration
cache.redis.host=${CACHE_REDIS_URL}
cache.redis.port=6379
cache.redis.lettuce.pool.max-active=8
cache.redis.lettuce.pool.max-idle=8
cache.redis.lettuce.pool.min-idle=2
cache.redis.lettuce.pool.max-wait=-1ms

# Redis logging
logging.level.org.springframework.data.redis=DEBUG
logging.level.io.lettuce.core=DEBUG

# logging
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# AWS Lambda
aws.lambda.personalized-recommendation.url=${LAMBDA_PERSONALIZED_URL}
aws.lambda.personalized-recommendation.timeout=10